### ISSUE TITLE
Debug build fail with clang-16

### ISSUE THREAD

**Issue by koliyo** [hylo-lang/Swifty-LLVM#22]
I can build in release mode as described in the readme file. But if I try debug build I get the following:

$ swift build -c debug  
Building for debugging...
clang-16: error: unknown argument: '-index-store-path'

Any pointers on how to resolve this?

In `.build/debug.yaml` I see

```yml
    description: "Compiling llvmshims src/shim.cc"
    args: ["/opt/homebrew/opt/ccache/libexec/clang",...,"-index-store-path"]
```

which is not part of `.build/release.yaml`

**Comment by kyouko-taiga** [comment]
Doesn't ring any bell on my end.
Could this be related to a beta version of Xcode?

It seems there might be [ways to to turn off the option](https://github.com/facebook/infer/issues/1470).

**Comment by koliyo** [comment]
I am not using beta XCode, my version is: 14.3.1 (14E300c)

I have clang/llvm installed via homebrew

Actually, I see now that this is the problem, swift build using the homebrew clang instead of xcode clang!

My `PATH` is configured to use homebrew clang +  ccache:

```
$ which clang
/opt/homebrew/opt/ccache/libexec/clang
```

And if I check where xcode clang is located

```
$ xcodebuild -find clang
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
```

and update `PATH` to use this instead, then the error goes away. 

So that makes sense.

But still a bit curious why release build does not use that flag.
